volumes:
    qm-docker-postgres-volume: null
    qm-docker-redis-volume: null
    qm-docker-minio-volume: null
    sail-meilisearch:
        driver: local
    sail-minio:
        driver: local

networks:
    sail:
        driver: bridge

services:
    ######## APP ########
    local:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - CONTAINER_ROLE=ALL
        volumes:
            - ".:/var/www/html"
            - "./start.sh:/usr/local/bin/start"
            - "./docker/xdebug-local.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
        ports:
            - "${FORWARD_APACHE_PORT:-80}:80"
        working_dir: /var/www/html
        depends_on:
            - qm-docker-postgres
            - qm-docker-redis
    
    ######## DATABASE ########
    qm-docker-postgres:
        image: postgres:14.2
        environment:
            - POSTGRES_DB=quantimodo_test
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret
        volumes:
            - qm-docker-postgres-volume:/var/lib/postgresql/data
        ports:
            - "${FORWARD_POSTGRES_PORT:-5432}:5432"
    
    ######## REDIS ########
    qm-docker-redis:
        image: redis:6.2.4
        volumes:
            - qm-docker-redis-volume:/data
        ports:
            - "6317:6379"

    memcached:
        image: 'memcached:alpine'
        ports:
            - '11211:11211'
        networks:
            - sail

    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health" ]
            retries: 3
            timeout: 5s

    minio:
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9001}:9000'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: 'sail'
            MINIO_ROOT_PASSWORD: 'password'
        volumes:
            - 'sail-minio:/data/minio'
        networks:
            - sail
        command: minio server /data/minio --console-address ":8900"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
            retries: 3
            timeout: 5s

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
