volumes:
    qm-docker-postgres-test-volume: null

networks:
    test-network:
        driver: bridge

services:
    phpunit:
        image: dfda-phpunit
        build:
            context: .
            dockerfile: Dockerfile.phpunit
        env_file: .env.testing
        volumes:
            - ".:/var/www/html"
            - "./test-deploy.sh:/usr/local/bin/test-deploy"
            - "./docker/xdebug-local.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
        networks:
            - test-network
        depends_on:
            - qm-docker-postgres
            - qm-docker-redis

    qm-docker-postgres:
        image: postgres:14.2
        environment:
            - POSTGRES_DB=${DB_TEST_DATABASE:-quantimodo_test}
            - POSTGRES_USER=${DB_TEST_USERNAME:-postgres}
            - POSTGRES_PASSWORD=${DB_TEST_PASSWORD:-secret}
        volumes:
            - qm-docker-postgres-test-volume:/var/lib/postgresql/data
        networks:
            - test-network

    qm-docker-redis:
        image: redis:6.2.4
        networks:
            - test-network 